api-version: 1.14
commands:
  tpl:
    uasge: giji34:tpl <X> <Y> <Z>
  tpb:
    usage: giji34:tpb <Name of Landmark>
  gm:
    usage: giji34:gm
  gfill:
  greplace:
  gundo:
  gregenerate:
  gtree:
    usage: gtree <幹の長さ>
  guide:
    usage: guide <Player> <Name of Landmark>
  follow:
    usage: follow <Player>
  create_portal:
    usage: create_portal <name> <returnX> <returnY> <returnZ>
  delete_portal:
    usage: delete_portal <name>
